# Generated by Django 3.2 on 2021-04-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('target_category', models.CharField(choices=[('specialized_first_aid', 'specialized_first_aid'), ('resucitation', 'resucitation'), ('stabilization', 'stabilization'), ('minor_aid_for_immediate_return_to_duty', 'minor_aid_for_immediate_return_to_duty'), ('initial_stress_management', 'initial_stress_management'), ('primary_disease_prevention', 'primary_disease_prevention'), ('prep_of_casulaties_for_evacuation_to_higher_level_treatment', 'prep_of_casulaties_for_evacuation_to_higher_level_treatment'), ('emergency_dental_care', 'emergency_dental_care'), ('establish_cause_of_death', 'establish_cause_of_death'), ('basic_laboratory_testing', 'basic_laboratory_testing'), ('patient_holding', 'patient_holding'), ('xrays', 'xrays'), ('damage_control_surgery', 'damage_control_surgery'), ('enhanced_laboratory_testing', 'enhanced_laboratory_testing'), ('dental', 'dental'), ('isolation_ward', 'isolation_ward'), ('shock_treatment', 'shock_treatment'), ('mental_health', 'mental_health'), ('intensive_care_unit', 'intensive_care_unit'), ('ctscan', 'ctscan'), ('prepare_patient_for_aeromed_evactuation', 'prepare_patient_for_aeromed_evactuation'), ('specialized_surgery', 'specialized_surgery'), ('emergency_gynaecological', 'emergency_gynaecological'), ('dental_surgery', 'dental_surgery'), ('longterm_patient_holding', 'longterm_patient_holding'), ('reconstructive_surgery', 'reconstructive_surgery'), ('blood_bank', 'blood_bank'), ('mortuary', 'mortuary')], default=('specialized_first_aid', 'specialized_first_aid'), max_length=255)),
            ],
        ),
    ]
