# Generated by Django 3.2 on 2021-04-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalCapabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1)),
                ('specialized_first_aid', models.BooleanField(default=False, verbose_name='Specialized First Aid')),
                ('resucitation', models.BooleanField(default=False, verbose_name='Resucitation')),
                ('stabilization', models.BooleanField(default=False, verbose_name='Stabilization')),
                ('minor_aid_for_immediate_return_to_duty', models.BooleanField(default=False, verbose_name='Minor aid for immediate return to duty')),
                ('initial_stress_management', models.BooleanField(default=False, verbose_name='Initial Stress Management')),
                ('primary_disease_prevention', models.BooleanField(default=False, verbose_name='Primary disease prevention')),
                ('prep_of_casulaties_for_evacuation_to_higher_level_treatment', models.BooleanField(default=False, verbose_name='Prep of casulaties for evacuation to higher level treatment')),
                ('emergency_dental_care', models.BooleanField(default=False, verbose_name='Emergency dental care')),
                ('establish_cause_of_death', models.BooleanField(default=False, verbose_name='Establish cause of death')),
                ('basic_laboratory_testing', models.BooleanField(default=False, verbose_name='Basic Laboratory Testing')),
                ('patient_holding', models.BooleanField(default=False, verbose_name='Patient holding')),
                ('xrays', models.BooleanField(default=False, verbose_name='X-Rays')),
                ('damage_control_surgery', models.BooleanField(default=False, verbose_name='Damage control surgery')),
                ('enhanced_laboratory_testing', models.BooleanField(default=False, verbose_name='Enhanced Laboratory Testing')),
                ('dental', models.BooleanField(default=False, verbose_name='Dental')),
                ('isolation_ward', models.BooleanField(default=False, verbose_name='Isolation Ward')),
                ('shock_treatment', models.BooleanField(default=False, verbose_name='Shock treatment')),
                ('mental_health', models.BooleanField(default=False, verbose_name='Mental health')),
                ('intensive_care_unit', models.BooleanField(default=False, verbose_name='Intensive Care Unit')),
                ('ctscan', models.BooleanField(default=False, verbose_name='CT-scan')),
                ('prepare_patient_for_aeromed_evactuation', models.BooleanField(default=False, verbose_name='Prepare patient for aeromed evactuation')),
                ('specialized_surgery', models.BooleanField(default=False, verbose_name='Specialized surgery')),
                ('emergency_gynaecological', models.BooleanField(default=False, verbose_name='Emergency gynaecological/obstretic care')),
                ('dental_surgery', models.BooleanField(default=False, verbose_name='Dental surgery')),
                ('longterm_patient_holding', models.BooleanField(default=False, verbose_name='Long-term patient holding')),
                ('reconstructive_surgery', models.BooleanField(default=False, verbose_name='Reconstructive surgery')),
                ('blood_bank', models.BooleanField(default=False, verbose_name='Blood bank')),
                ('mortuary', models.BooleanField(default=False, verbose_name='Mortuary')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('patient_capacity', models.PositiveIntegerField(verbose_name='Patient capacity')),
                ('patients_at_the_start', models.PositiveIntegerField(verbose_name='No. of patients at the start')),
                ('free_patient', models.IntegerField(verbose_name='FREE patients')),
                ('total_beds_for_patient_holding', models.PositiveIntegerField(verbose_name='Total beds for patient holding')),
                ('total_beds_occupied', models.PositiveIntegerField(verbose_name='Total beds occupied')),
                ('free_beds', models.IntegerField(verbose_name='FREE beds')),
                ('total_operating_tables', models.PositiveIntegerField(verbose_name='Total operating tables')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospitalcapabilities')),
            ],
        ),
    ]
