# Generated by Django 3.2 on 2021-04-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210412_1800'),
    ]

    def generate_hospital_types(apps, schema_editor):
        from hospital.models import HospitalCapabilities

        h1 = HospitalCapabilities()
        h1.type = HospitalCapabilities.TYPES[0][0]
        h1.save()

        h2 = HospitalCapabilities()
        h2.type = HospitalCapabilities.TYPES[1][0]
        h2.save()

        h3 = HospitalCapabilities()
        h3.type = HospitalCapabilities.TYPES[2][0]
        h3.save()

        h4 = HospitalCapabilities()
        h4.type = HospitalCapabilities.TYPES[3][0]
        h4.save()

    operations = [
        migrations.RunPython(generate_hospital_types),
    ]
