# Generated by Django 3.2 on 2021-04-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20210412_1803'),
    ]

    def generate_hospitals(apps, schema_editor):
        from hospital.models import Hospital, HospitalCapabilities

        ht_a = HospitalCapabilities.objects.filter(type="A").first()
        ht_b = HospitalCapabilities.objects.filter(type="B").first()
        ht_c = HospitalCapabilities.objects.filter(type="C").first()


        h1 = Hospital()
        h1.name = "MF - C- 1"
        h1.type = ht_c
        h1.patient_capacity = 60
        h1.patients_at_the_start = 54
        h1.free_patient = 6
        h1.total_beds_for_patient_holding = 7
        h1.total_beds_occupied = 3
        h1.free_beds = 4
        h1.total_operating_tables = 3
        h1.save()

        h2 = Hospital()
        h2.name = "MF - B - 1"
        h2.type = ht_b
        h2.patient_capacity = 45
        h2.patients_at_the_start = 41
        h2.free_patient = 4
        h2.total_beds_for_patient_holding = 4
        h2.total_beds_occupied = 0
        h2.free_beds = 4
        h2.total_operating_tables = 2
        h2.save()

        h3 = Hospital()
        h3.name = "MF - A - 1"
        h3.type = ht_a
        h3.patient_capacity = 15
        h3.patients_at_the_start = 8
        h3.free_patient = 7
        h3.total_beds_for_patient_holding = 0
        h3.total_beds_occupied = 0
        h3.free_beds = 0
        h3.total_operating_tables = 0
        h3.save()

        h4 = Hospital()
        h4.name = "MF - A - 2"
        h4.type = ht_a
        h4.patient_capacity = 10
        h4.patients_at_the_start = 7
        h4.free_patient = 3
        h4.total_beds_for_patient_holding = 0
        h4.total_beds_occupied = 0
        h4.free_beds = 0
        h4.total_operating_tables = 0
        h4.save()

        h5 = Hospital()
        h5.name = "MF - A - 3"
        h5.type = ht_a
        h5.patient_capacity = 15
        h5.patients_at_the_start = 10
        h5.free_patient = 5
        h5.total_beds_for_patient_holding = 0
        h5.total_beds_occupied = 0
        h5.free_beds = 0
        h5.total_operating_tables = 0
        h5.save()

        h6 = Hospital()
        h6.name = "MF - A - 4"
        h6.type = ht_a
        h6.patient_capacity = 12
        h6.patients_at_the_start = 3
        h6.free_patient = 9
        h6.total_beds_for_patient_holding = 0
        h6.total_beds_occupied = 0
        h6.free_beds = 0
        h6.total_operating_tables = 0
        h6.save()

    operations = [
        migrations.RunPython(generate_hospitals),
    ]
