# Generated by Django 3.2 on 2021-04-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210412_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='grid_x',
            field=models.PositiveIntegerField(default=0, verbose_name='X position on the map'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='grid_y',
            field=models.PositiveIntegerField(default=0, verbose_name='Y position on the map'),
        ),
    ]
