# Generated by Django 3.2 on 2021-04-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Scenario')),
                ('patient_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Patient id')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('patient_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Patient type')),
                ('mechanism_of_injury', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mechanism of injury')),
                ('injury', models.CharField(blank=True, max_length=255, null=True, verbose_name='Injury')),
                ('course_of_action', models.CharField(blank=True, max_length=255, null=True, verbose_name='Course of action')),
                ('surgery', models.CharField(blank=True, max_length=255, null=True, verbose_name='Surgery')),
                ('immediate_return_to_duty', models.CharField(blank=True, max_length=255, null=True, verbose_name='Immediate return to duty')),
                ('triage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Triage')),
                ('expected_days_hold', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected days hold')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
            ],
        ),
    ]
