# Generated by Django 3.2 on 2021-04-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='grid_x',
            field=models.PositiveIntegerField(default=0, verbose_name='X position on the map'),
        ),
        migrations.AddField(
            model_name='patient',
            name='grid_y',
            field=models.PositiveIntegerField(default=0, verbose_name='Y position on the map'),
        ),
    ]
