# Generated by Django 3.2 on 2021-04-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20210413_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='grid_x',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='X position on the map'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='grid_y',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Y position on the map'),
        ),
    ]
