# Generated by Django 3.2 on 2021-04-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20210414_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_transported_to_hospital_with_free_beds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_transported_to_hospital_with_specializations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='tried_evacute_immediate_with_result',
            field=models.BooleanField(default=False),
        ),
    ]
