version: "3.9"
services:
  frontend:
    build: "."
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - ./node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'


#      version: "3.9"
#      services:
#        frontend:
#          build: ./hackatonfrontend
#          ports:
#            - 3000:3000
#          volumes:
#            - ./hackatonfrontend/:/frontend/
#            - /hackatonfrontend/node_modules
#          environment:
#            CHOKIDAR_USEPOLLING: 'true'

networks:
  default:
    external:
      name: hackathonbackend_default
